<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
             <a href="#" id="<?php echo $_product->getName() ?>" class="product-inquiry"><?php /* @escapeNotVerified */ echo __('Enquire Now') ?></a>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<!--facebook share-->
<div class="fb-share-button" data-href="<?php echo 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']; ?>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>
<!--facebook share-->
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<div id="nnquiry-mpdal" class="product-inquiry-content" style="display:none;">
   <!--  <legend class="legend"><span><h1> Product Inquiry.. </h1></span></legend><br> -->
        <form action="" id="inquiry-form" class="inquiry-form" data-mage-init='{"validation": {}}'>
          <fieldset class="fieldset">
         <div class="field name required">
            <label class="label"><span>Product</span></label>
            <div class="control">
                <input name="pname" id="pname" title="Product Name" value="<?php echo $_product->getName(); ?>" class="pname input-text required-entry" type="text">
            </div>
        </div>
          <div class="field name required">
            <label class="label"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Your Name" value="" class="input-text required-entry" type="text">
            </div>
        </div>
          <div class="field email required">
            <label class="label" for="email"><span>Email</span></label>
            <div class="control">
                <input name="email" id="email" title="Email" value="" class="input-text required-entry" type="email">
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span>About Enquiry</span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="What’s on your mind?" class="input-text required-entry" cols="5" rows="3" aria-required="true"></textarea>
            </div>
        </div>
          <!-- <input type="submit" value="Submit"> -->
        </fieldset>
    </form>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal',
            'mage/mage'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Know about product',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                         var values = {};
                         var thismodal = this;
                         var dataForm = $('#inquiry-form');
                         var formValid = dataForm.mage('validation', {});
                         if($(formValid).validation('isValid'))
                        {
                            $("form.inquiry-form :input").each(function(){
                             var input = $(this);
                             values[this.name] = $(this).val();
                            });
                             $.ajax({
                                type:"POST",
                                cache:false,
                                url:"productinquiry",
                                data:{ formdata : values },
                                success: function (html) {
                                     if(html == 1)
                                   {
                                      thismodal.closeModal();
                                   }else{
                                         thismodal.closeModal();
                                        //location.reload();
                                   }
                                }
                              });
                        }
                    }
                }]
            };

            var popup = modal(options, $('#nnquiry-mpdal'));
            $(".product-inquiry").on('click',function(){ 
                var pname = $(this).attr('id');
                $('.pname').val(pname);
                $("#nnquiry-mpdal").modal("openModal");
            });

        }
    );
</script>
<script type="text/x-magento-init">
    {
        "#inquiry-form": {
            "validation": {}
        }
    }
</script>