<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
        <?php 
        /*test*/
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $baseUrl = $storeManager->getStore()->getBaseUrl();
        $categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
        $categories = $categoryHelper->getStoreCategories();
        $CurrentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
		echo "<div class='sorting-by-category'>";
		echo "<label class='sorter-label'>View</label>";
        echo "<select class='sorter-options category'>";
        foreach ($categories as $category) {  
        ?>  
           <option <?php if ($category->getId() == $CurrentCategory->getId()) { ?>selected="selected"<?php } ?> value="<?php echo $category->getRequestPath() ?>"><?php echo $category->getName(); ?></option>
        <?php
        }
        echo "</select>";
		echo "</div>";
        /*test*/
        ?>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
        <?php //include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        <?php echo $block->getPagerHtml() ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
<?php endif ?>
<script type="text/javascript">
require([
  'jquery',
  'jquery/ui'
], function($){
    $("select.sorter-options").change(function()
    {
        var selectedCate = $(".sorter-options option:selected").val();
        window.location = "<?php echo $baseUrl ?>"+selectedCate;
    });
  });
</script>